version: '3'
volumes:
  onfhirdata:
    driver: local
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - onfhirdata:/data/db
  onfhir:
    image: srdc/onfhir:r4
    container_name: onfhir
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - APP_CONF_FILE=/usr/local/onfhir/conf/application-docker.conf
      - FHIR_ROOT_URL=http://127.0.0.1:8080/fhir
      - DB_EMBEDDED=false
      - DB_HOST=mongo:27017
    ports:
      - "8080:8080"
    volumes:
      - ./sample-setup/conf:/usr/local/onfhir/conf
