FROM openjdk:11-jre-slim

# We need curl for healthcheck
RUN apt -y update; apt -y install curl

ENV ONFHIR_HOME /usr/local/onfhir
RUN mkdir -p "$ONFHIR_HOME"
WORKDIR $ONFHIR_HOME

COPY ./onfhir-server-r5/target/onfhir-server-standalone.jar .
COPY ./docker/docker-entrypoint.sh .
RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
